// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function ExecuteQuery(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteQuery'](arg1, arg2, arg3);
}

export function GetConnectionSettings(arg1) {
  return window['go']['main']['App']['GetConnectionSettings'](arg1);
}

export function GetConnectionsNames() {
  return window['go']['main']['App']['GetConnectionsNames']();
}

export function GetServerDatabases(arg1) {
  return window['go']['main']['App']['GetServerDatabases'](arg1);
}

export function GetServerDbSchemas(arg1, arg2) {
  return window['go']['main']['App']['GetServerDbSchemas'](arg1, arg2);
}

export function GetServerDbTables(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetServerDbTables'](arg1, arg2, arg3);
}

export function GetTableIndexes(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetTableIndexes'](arg1, arg2, arg3, arg4);
}

export function GetTableKeys(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetTableKeys'](arg1, arg2, arg3, arg4);
}

export function GetTableStructure(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetTableStructure'](arg1, arg2, arg3, arg4);
}

export function InitConnections() {
  return window['go']['main']['App']['InitConnections']();
}

export function PingConnection(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PingConnection'](arg1, arg2, arg3, arg4);
}

export function SaveConnectionSettings(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveConnectionSettings'](arg1, arg2, arg3, arg4, arg5);
}

export function SetDbServer(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetDbServer'](arg1, arg2, arg3, arg4, arg5);
}
