// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExecuteQuery(arg1:string,arg2:string,arg3:string):Promise<Array<any>>;

export function GetConnectionSettings(arg1:string):Promise<main.ConnectionSettings>;

export function GetConnectionsNames():Promise<Array<string>>;

export function GetServerDatabases(arg1:string):Promise<Array<string>>;

export function GetServerDbSchemas(arg1:string,arg2:string):Promise<Array<string>>;

export function GetServerDbTables(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;

export function GetTableStructure(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<any>>;

export function InitConnections():Promise<void>;

export function PingConnection(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveConnectionSettings(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function SetDbServer(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;
